Cioos Release 1.3.0  (#174)
* Rename lib/io.py module which was giving problems

* Rename __init__.py file in extension

* Show job title on job start/finish log messages

To make it easier to debug background job calls.

Before:

```
INFO  [ckan.lib.jobs] Worker rq:worker:f0792c8bd67344f288b5704d39c43124 starts job 2baa42e5-4582-4103-92e5-b4a384d0b1da from queue "default"
```

After:

```
INFO  [ckan.lib.jobs] Worker rq:worker:f0792c8bd67344f288b5704d39c43124 starts job 2baa42e5-4582-4103-92e5-b4a384d0b1da (Process data fields) from queue "default"
```

* Add missing __init__.py file

* String literals

* snippet names rendered in non-debug mode

* Update changelog for 2.9.4

* Build frontend

* [i18n] Pull po files from Transifex

* [i18n] Compile mo files

* Upgrade version for 2.9.4

* Update version for 2.9.5b

* Consistent cli behavior

* pep8

* Py2 compatible fix for #6135

* [#6390] fix user create/edit email validators

* Allow strict types for user/group uploads

CKAN 2.9 specific changes when cherry-picking:

* Replace f-strings with .format()
* Don't use faker / Pillow for tests, as there is no faker fixture in
the Python 2 version

* Add changelog entry for group image types

* Move type verification into upload method

* Fix APIToken CLI test

* Update docs

* Link to config options from changelog

* Allow children for select2

* Fix children type

* [#6531] Py2/py3 compatible version of open

* Add select2 features

* Undo change

* Replace f-string

* Fix standards

* [#6530] Add Solr 8 support

* Set logging level to error in error mail handler

* Add RootPathMiddleware to flask stack to support non-root installs running on python 3

* Add previously removed RootPathMiddleware back to common middleware as it is still needed

* Added utility functions for common CKAN admin commands.

* Use correct auth function when editing organizations

* [#5820] fix invite user with existing email error

* Fix regression when validating resource subfields (by @TomeCirun)

* [#6408] Add timeout param to request get calls (by @EricSoroos)

* [#6408] Document new options

* Accept empty string in one of validator

* Negate empty string check

* Fix pep8

* [i18n] Pull translation from Transifex

* [i18n] Compile mo files

* Compile frontend

* Small fix adding virtual env path to ckan command.

* Update changelog before 2.9.5

* Include the Solr 8 schema file in the 2.9 branch

* Update version for 2.9.5

* Update version for 2.9.6b

* Unpin pytz (#6665)

* Pytz is a stable package, and should always be at the most recent version

* Pin zope.interface to a more recent version (#6665)

* Supports py3 > 3.5
* Allows for modern setuptools > 44.1

* fix errno2

* Add Dockerfile.py3 based on d9a49a842863c97f2358a31167cba66d2050a8b8

* Check if locale exists on i18n JS API

* Add test and changelog

* Updates to ckan_utils.sh.

* move spatial harvester into ckanext-cioos_harvest extension and allow POST requests to the spatial search api endpoint in the spatial api

* document spatil harvester config

* update submodules

* create dev branch in submodules and update

* remove extra comma

(cherry picked from commit fb27f2a42cd9b579e1989271f5ecf1a3f4c4e35d)

* Fixing tests.

* --passthrough-errors overrides conflicting options

* Describe --passthrough-errors

* Add --passthrough-errors example inside docker-compose.yml

* Disable reloader when passthrough_errors is set

* Add --host 0.0.0.0 to pdb example

* add try/except block when creating test data

* add compile css command

* check for data before attempting to create it again

* upgrade solr to 8.11.1

* update

* update all submodules to latest dev version

* update submodules again

* update schema

* Updated submodule contrib/docker/src/ckanext-cioos_theme

* Updated submodule contrib/docker/src/ckanext-spatial

* fix a few integration bugs

* update

* Updated submodule contrib/docker/src/ckanext-cioos_theme

* update translations

* fix bugs, update logos

* Updated submodule contrib/docker/src/ckanext-scheming

* add atlantic eov icons

* Updated submodule contrib/docker/src/ckanext-cioos_theme

* add collapsed option to indicate how truncated fields initially load

* add wasRevisionOf to schema.org profile output

* release all submodules -  merge dev into main

* remove geoview pip file from dockerfile

* Merge branch 'cioos' into cioos_dev
Removed submodule contrib/docker/src/ckanext-cioos_theme

* Fixes a two errors when dealing with a encoded url.

* url in question /%EF%AC%81?foo=bar&bz=%AC%81
* This is a unicode character, which can't be decoded from
ascii. Jinja templates will handle this if it's unicode, or if it's
hex encoded ascii, but can't take a non-unicode string in python 2 and
put this in a template.
* The querystring was being quoted, which is incorrect, as:
  1) the special characters in the query string mean something
  2) The rest of the querystring is already quoted. This makes it
  double quoted, as seen in the datastore file
* We don't want to unquote urls before putting them in the template
anyway.
* There was s further error passing this unicode path to the template
resolution, where in posix path, it fails:
```
File '/usr/lib/ckan/default/lib/python2.7/posixpath.py', line 73 in join
  path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 1: ordinal not in range(128)
```
The solution here is to make sure it's unicode passed into the
function.

* check for resource

* Fix urlparse function call

* [#6948] Avoid storing the session on each request

Override the `is_null_session()` method on our own custom
`BeakerSessionInterface` class to take into account that Beaker always
adds two keys to the session.

* [#6948] Add tests to ensure we don't create unneeed sessions

Move the BeakerSessionInterface class to make testing easier

* [#6948] pep8

* [#6948] prefix literal

* [#6948] Add more keys for Beaker==1.11.0 (py3)

* [#6948] Prefixes

* [#6948] Cross-py version compatible fix

* [#6948] line too long

* [#6948] [#6984] More elegant check, thanks @ThrawnCA

* [#6948] pep8

* update

* update

* Fix additional casting error (str(unicode)->ascii decode error)

* add helper csrf_input

* replaced package_read with package_show

* [#5727] Fix datapusher trigger in case of resource_update without changing URL but using new file via API

The notify method in the IResourceUrlChange will be triggered only
when the URL is changed or if we do the resource update via the API
_submit_to_datapusher will not be triggered and cause the old preview to be displayed.

* [#5727] Add the changelog

* add organization facets

* Expose check_ckan_version to templates

* add try/except block when creating test data

* check for data before attempting to create it again

* Return zero results instead of raising NotFound when vocabulary does not exist

* [#5822] Update sqlparse version

* reorder resource view button: allow translation

* check if dir already exists

* lint

* remove white space

* Exclude site_user from user_list

* Remove typing from cherry-pick

* [QOL-8368] fix race condition in creating the default site user

- creating the user is idempotent so just ignore the error

* [#6649] gettext not for metadata fields

* [#6743] Include root_path in activity email notifications

* [#5857] Extract translations from emails

* Improve error when downloading resource

* Views return 403 for NotAuthorized

* [#6838] Use the headers Reply-to value if its set in the extensions

* Fix broken URL in migration docs

* ckan_config test mark works with request context

* Fix caching logic on logged in users

* [#6892] Fix member delete

* Fix relative import

* Handle missing resources in activity stream

* [#6439] Concurrent-safe resource updates

* Fix tests after #6820

* lint

* Fix tests after #6618

* prefixes

* Remove duplicated class

* add auth functions for 17 actions that didn't have them before

* add bilingual support to resource names

* fix formatting to satisfy linter

* remove new auth functions from blacklist

* add auth function for recently_changed_packages_activity_list

* remove recently_changed_packages_activity_list from blacklist

* document sitemap generation

* add sitemap url to docs

* [2.9] Bump markdown requirement to support Python 3.9

* update psycopg2 to support PostgreSQL 12, #5796

* [#6789] Fix error when listing tokens in the CLI in py2

* [#6519] Use get_action in patch actions to allow custom logic

* [#6658] Fix not_empty validator to allow falsy values

* [#6956] Prevent non-sysadmin users to change their own state

* [i18n] Pull translations from Transifex for 2.9.6

* [i18n] Compile mo files

* Add user_patch action

Needed for the #6956 fix

* Fix patch for #6956

* Frontend build

* lint

* Fix resource file size not updating with resource_patch

* Added changelog fragment

* [#6817] Fix theme settings

* Replace characters in url

* Fix url check location

* Use user id in auth cookie rather than name

* [#6815] Allow get_translated helper to fall back to base version of a language

* lint

* lint2

* Updated submodule contrib/docker/src/ckanext-cioos_theme

* Update CHANGELOG before 2.9.6

* Update version for 2.9.6

* Update version for 2.9.7b

* Updated submodule contrib/docker/src/ckanext-spatial

* Revert deletion portions of f9084f909538a963b1121d5cfb1e3a1485324add

* Restores main_css as an app global
* Restores helpsrs.get_rtl_theme

* Reset the form after downloading

* Perform checks on provided id when creating user

* [#7149] Fix organization delete form (via @Zharktas)

* Update changelog

* Update version for 2.9.7

* fix install docs

* add support for multilingual resource description and name

* make uri's more visible in the interface

* make uri handling more robust and clean up org about page

* fix translations

* merge in subrepo changes

* update sub repos

* match eov labels to munged  keywords

* add missing organization uri display in media grid view

* add fq to organization_list api endpoint

example query ```/api/3/action/organization_list?q=hakai&all_fields=true&include_extras=true&fq=-organization-uri:code"_ "",&fq=organization-uri:__```

* upgrade postgis to 3.3

* document organization_list fq addition

* add matching on org uri during harvest.
consolidate uri fields into code field when possible.

* update submodules

* Updates to functions in ckan_utils.sh.

* add harvest object delete chunk instructions

* Remove duplicate function, minor edits on ckan_utils.sh.

* fix organization matching on UID during ckan harvest

* Update the production.ini as variable, and change ec dump/load to generic functions.

* Minor fix to ckan_utils.sh.

* Updated submodule contrib/docker/src/ckanext-cioos_harvest

* update delete harvest objects by chunks code

* upgrade ckanext-harvest tp 1.4.1

* adjust get_fully_qualified_package_uri

* update submodules

* better populate resources during a cioos ckan harvest

* allow round brackets in keywords

* Updated submodule contrib/docker/src/ckanext-cioos_theme

* add tips to instructions doc

* [#175] Add or relocate volumes for solr and redis data in docker-compose files (#176)

* update pacific css

* add WSP logo

Co-authored-by: amercader <amercadero@gmail.com>
Co-authored-by: Sergey Motornyuk <sergey.motornyuk@linkdigital.com.au>
Co-authored-by: calexandr <cherniavskyi.alexandr@linkdigital.com.au>
Co-authored-by: Andres Vazquez <andres@data99.com.ar>
Co-authored-by: Francesco Frassinelli <francesco.frassinelli@nina.no>
Co-authored-by: Jari Voutilainen <jari.voutilainen@iki.fi>
Co-authored-by: Teemu Erkkola <teemu.erkkola@gofore.com>
Co-authored-by: Jeff Cullis <jcullis@dal.ca>
Co-authored-by: Eric Soroos <eric@derilinx.com>
Co-authored-by: cirun <bitola@Bitolas-MacBook-Pro.local>
Co-authored-by: Tome Cirun <cirun@live.com>
Co-authored-by: Tomasz Sabała <tomek@fjelltopp.org>
Co-authored-by: Sergey <tonnydexter@gmail.com>
Co-authored-by: hq-ods <hao.qin@ontario.ca>
Co-authored-by: Shubham Mahajan <mr.shubhammahajan@gmail.com>
Co-authored-by: Sunny-NEC <t_sunny.malik@india.nec.com>
Co-authored-by: Ian Ward <ian@excess.org>
Co-authored-by: Tome Cirun <cirun@pop-os.localdomain>
Co-authored-by: ThrawnCA <shell_layer-github@yahoo.com.au>
Co-authored-by: pdelboca <patriciodelboca@gmail.com>
Co-authored-by: Knud Möller <dunken69@gmail.com>
Co-authored-by: antuarc <carl.antuar@smartservice.qld.gov.au>
Co-authored-by: Konstantin Sivakov <konstantin.sivakov@gmail.com>
Co-authored-by: Jari Voutilainen <jari-pekka.voutilainen@gofore.com>
Co-authored-by: I G Borrelli <44072946+ItaloBorrelli@users.noreply.github.com>